[package]
name = "rust-crypto"
version = "0.1.1"
authors = ["The Rust-Crypto Project Developers"]
license = "MIT/Apache-2.0"
homepage = "https://github.com/DaGenix/rust-crypto/"
repository = "https://github.com/DaGenix/rust-crypto/"
description = "A (mostly) pure-Rust implementation of various common cryptographic algorithms."
keywords = [
    "Cryptography",
    "Crypto",
    "MD5",
    "RIPEMD-160",
    "Sha1",
    "Sha2",
    "HMAC",
    "PBKDF2",
    "Scrypt",
    "AES",
    "RC4",
    "Salsa20",
    "XSalsa20",
    "Blowfish",
    "Bcrypt",
    "Blake2B",
    "ChaCha20",
    "Fortuna",
    "Ghash",
    "Poly1305"
]
readme = "README.md"

[lib]
name = "rust-crypto"
path = "src/rust-crypto/lib.rs"

[[bin]]
name = "rust-crypto-util"
path = "src/rust-crypto-util/tool.rs"
test = false
bench = false

[profile.test]
opt-level = 2

[dependencies]
time = "*"
